// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unsxalrrgteywxjgeyqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuc3hhbHJyZ3RleXd4amdleXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzY1MDEsImV4cCI6MjA2ODAxMjUwMX0.X4BmXEVVx53Mzcy3rqeFM16PzdzpriB0HgHHHaNIQJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});